wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.6
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      4: 3.7.6
      5: 0.10.31
      8:
      - 2
      - 3
      - 5
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 5.5e-05
num_epochs:
  desc: null
  value: 2
