wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.1
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.8.1
      5: 0.10.32
      8:
      - 5
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 5.5e-05
num_epochs:
  desc: null
  value: 10
num_workers:
  desc: null
  value: 4
