name: "Linting and Flaking"

on:
  push:
    branches: [ wandb-ci ]
  pull_request:
    branches: [ wandb-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.1
    - name: Sort packages
      run: |
        pip install isort
        isort .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .